config/routes.rb
PortalBrazucas::Application.routes.draw do
  resources :comentarios

  resources :noticia

  resources :anuncios

  resources :anunciantes

  resources :visitante_credenciados

  devise_for :usuarios, :controllers => { :registrations => "registrations" }

  get "home/index"
  get "home/tipo_conta"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

    root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/anunciante.rb
class Anunciante < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :endereco
  has_many :anuncios
  attr_accessible :cnpj, :nome, :razao_social, :telefone, :url_website, :usuario, :endereco
end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  belongs_to :anunciante
  attr_accessible :descricao, :titulo, :url_anuncio
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  belongs_to :estado
  has_many :enderecos
  attr_accessible :altitude, :area, :clima, :densidade, :fuso_horario, :nome, :populacao, :sigla, :url_website, :estado
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :noticia
  attr_accessible :texto
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  attr_accessible :bairro, :cidade, :complemento, :latitude, :logradouro, :longitude, :numero
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_many :cidades
  attr_accessible :nome, :sigla, :pais
end

app/models/noticium.rb
class Noticium < ActiveRecord::Base
  attr_accessible :autor, :conteudo, :fonte, :titulo
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_many :estados
  attr_accessible :nome, :sigla, :url_imagem_bandeira
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :visitante_credenciados
  has_many :anunciantes
end

app/models/visitante_credenciado.rb
class VisitanteCredenciado < ActiveRecord::Base
  belongs_to :usuario
  attr_accessible :cpf, :nascimento, :nome, :sexo, :sobrenome, :telefone, :usuario
end

app/controllers/anunciantes_controller.rb
class AnunciantesController < InheritedResources::Base
  
  # GET /anunciantes
  # GET /anunciantes.json
  def index
    @anunciantes = Anunciante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anunciantes }
    end
  end

  # GET /anunciantes/1
  # GET /anunciantes/1.json
  def show
    @anunciante = Anunciante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anunciante }
    end
  end

  # GET /anunciantes/new
  # GET /anunciantes/new.json
  def new
    @anunciante = Anunciante.new
    @anunciante.usuario = current_usuario

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anunciante }
    end
  end

  # GET /anunciantes/1/edit
  def edit
    @anunciante = Anunciante.find(params[:id])
  end

  # POST /anunciantes
  # POST /anunciantes.json
  def create
    @anunciante = Anunciante.new(params[:anunciante])
    @anunciante.usuario = current_usuario

    respond_to do |format|
      if @anunciante.save
        format.html { redirect_to @anunciante, notice: 'Jogo was successfully created.' }
        format.json { render json: @anunciante, status: :created, location: @anunciante }
      else
        format.html { render action: "new" }
        format.json { render json: @anunciante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anunciantes/1
  # PUT /anunciantes/1.json
  def update
    @anunciante = Anunciante.find(params[:id])

    respond_to do |format|
      if @anunciante.update_attributes(params[:anunciante])
        format.html { redirect_to @anunciante, notice: 'Jogo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anunciante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anunciantes/1
  # DELETE /anunciantes/1.json
  def destroy
    @anunciante = Anunciante.find(params[:id])
    @anunciante.destroy

    respond_to do |format|
      format.html { redirect_to anunciantes_url }
      format.json { head :no_content }
    end
  
  end
  
  
end

app/controllers/anuncios_controller.rb
class AnunciosController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
  end
  
  def tipo_conta
    
  end
  
end

app/controllers/noticia_controller.rb
class NoticiaController < InheritedResources::Base
end

app/controllers/visitante_credenciados_controller.rb
class VisitanteCredenciadosController < InheritedResources::Base
  
  
  
  # GET /visitante_credenciados
  # GET /visitante_credenciados.json
  def index
    @visitante_credenciados = VisitanteCredenciado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visitante_credenciados }
    end
  end

  # GET /visitante_credenciados/1
  # GET /visitante_credenciados/1.json
  def show
    @visitante_credenciado = VisitanteCredenciado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visitante_credenciado }
    end
  end

  # GET /visitante_credenciados/new
  # GET /visitante_credenciados/new.json
  def new
    @visitante_credenciado = VisitanteCredenciado.new
    @visitante_credenciado.usuario = current_usuario

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visitante_credenciado }
    end
  end

  # GET /visitante_credenciados/1/edit
  def edit
    @visitante_credenciado = VisitanteCredenciado.find(params[:id])
  end

  # POST /visitante_credenciados
  # POST /visitante_credenciados.json
  def create
    @visitante_credenciado = VisitanteCredenciado.new(params[:visitante_credenciado])
    @visitante_credenciado.usuario = current_usuario

    respond_to do |format|
      if @visitante_credenciado.save
        format.html { redirect_to @visitante_credenciado, notice: 'Jogo was successfully created.' }
        format.json { render json: @visitante_credenciado, status: :created, location: @visitante_credenciado }
      else
        format.html { render action: "new" }
        format.json { render json: @visitante_credenciado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visitante_credenciados/1
  # PUT /visitante_credenciados/1.json
  def update
    @visitante_credenciado = VisitanteCredenciado.find(params[:id])

    respond_to do |format|
      if @visitante_credenciado.update_attributes(params[:visitante_credenciado])
        format.html { redirect_to @visitante_credenciado, notice: 'Jogo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visitante_credenciado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitante_credenciados/1
  # DELETE /visitante_credenciados/1.json
  def destroy
    @visitante_credenciado = VisitanteCredenciado.find(params[:id])
    @visitante_credenciado.destroy

    respond_to do |format|
      format.html { redirect_to visitante_credenciados_url }
      format.json { head :no_content }
    end
  
  end
end

app/helpers/anunciantes_helper.rb
module AnunciantesHelper
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/visitante_credenciados_helper.rb
module VisitanteCredenciadosHelper
end

app/views/visitante_credenciados/_form.html.erb
<%= form_for(@visitante_credenciado) do |f| %>
  <% if @visitante_credenciado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visitante_credenciado.errors.count, "error") %> prohibited this visitante_credenciado from being saved:</h2>

      <ul>
      <% @visitante_credenciado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	
  <div class="field">
    <%= @visitante_credenciado.usuario.id %><br />
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sobrenome %><br />
    <%= f.text_field :sobrenome %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :nascimento %><br />
    <%= f.date_select :nascimento %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visitante_credenciados/edit.html.erb
<h1>Editing visitante_credenciado</h1>

<%= render 'form' %>

<%= link_to 'Show', @visitante_credenciado %> |
<%= link_to 'Back', visitante_credenciados_path %>

app/views/visitante_credenciados/index.html.erb
<h1>Listing visitante_credenciados</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Sexo</th>
    <th>Nascimento</th>
    <th>Telefone</th>
    <th>Cpf</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visitante_credenciados.each do |visitante_credenciado| %>
  <tr>
    <td><%= visitante_credenciado.usuario %></td>
    <td><%= visitante_credenciado.nome %></td>
    <td><%= visitante_credenciado.sobrenome %></td>
    <td><%= visitante_credenciado.sexo %></td>
    <td><%= visitante_credenciado.nascimento %></td>
    <td><%= visitante_credenciado.telefone %></td>
    <td><%= visitante_credenciado.cpf %></td>
    <td><%= link_to 'Show', visitante_credenciado %></td>
    <td><%= link_to 'Edit', edit_visitante_credenciado_path(visitante_credenciado) %></td>
    <td><%= link_to 'Destroy', visitante_credenciado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visitante credenciado', new_visitante_credenciado_path %>

app/views/visitante_credenciados/new.html.erb
<h1>New visitante_credenciado</h1>

<%= render 'form' %>

<%= link_to 'Back', visitante_credenciados_path %>

app/views/visitante_credenciados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @visitante_credenciado.usuario.email  %>
</p>

<p>
  <b>Nome:</b>
  <%= @visitante_credenciado.nome %>
</p>

<p>
  <b>Sobrenome:</b>
  <%= @visitante_credenciado.sobrenome %>
</p>

<p>
  <b>Sexo:</b>
  <%= @visitante_credenciado.sexo %>
</p>

<p>
  <b>Nascimento:</b>
  <%= @visitante_credenciado.nascimento %>
</p>

<p>
  <b>Telefone:</b>
  <%= @visitante_credenciado.telefone %>
</p>

<p>
  <b>Cpf:</b>
  <%= @visitante_credenciado.cpf %>
</p>


<%= link_to 'Edit', edit_visitante_credenciado_path(@visitante_credenciado) %> |
<%= link_to 'Back', visitante_credenciados_path %>