config/routes.rb
PortalBrazucas::Application.routes.draw do
  resources :comentarios

  resources :noticia

  resources :anuncios

  resources :anunciantes

  resources :visitante_credenciados

  devise_for :usuarios, :controllers => { :registrations => "registrations" }

  get "home/index"
  get "home/tipo_conta"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

    root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/anunciante.rb
class Anunciante < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :endereco
  has_many :anuncios
  attr_accessible :cnpj, :nome, :razao_social, :telefone, :url_website, :usuario, :endereco
end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  belongs_to :anunciante
  attr_accessible :descricao, :titulo, :url_anuncio
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  belongs_to :estado
  has_many :enderecos
  attr_accessible :altitude, :area, :clima, :densidade, :fuso_horario, :nome, :populacao, :sigla, :url_website, :estado
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :noticia
  attr_accessible :texto
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  attr_accessible :bairro, :cidade, :complemento, :latitude, :logradouro, :longitude, :numero
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_many :cidades
  attr_accessible :nome, :sigla, :pais
end

app/models/noticium.rb
class Noticium < ActiveRecord::Base
  attr_accessible :autor, :conteudo, :fonte, :titulo
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_many :estados
  attr_accessible :nome, :sigla, :url_imagem_bandeira
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :visitante_credenciados
  has_many :anunciantes
end

app/models/visitante_credenciado.rb
class VisitanteCredenciado < ActiveRecord::Base
  belongs_to :usuario
  attr_accessible :cpf, :nascimento, :nome, :sexo, :sobrenome, :telefone, :usuario
end

app/controllers/anunciantes_controller.rb
class AnunciantesController < InheritedResources::Base
  
  # GET /anunciantes
  # GET /anunciantes.json
  def index
    @anunciantes = Anunciante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anunciantes }
    end
  end

  # GET /anunciantes/1
  # GET /anunciantes/1.json
  def show
    @anunciante = Anunciante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anunciante }
    end
  end

  # GET /anunciantes/new
  # GET /anunciantes/new.json
  def new
    @anunciante = Anunciante.new
    @anunciante.usuario = current_usuario

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anunciante }
    end
  end

  # GET /anunciantes/1/edit
  def edit
    @anunciante = Anunciante.find(params[:id])
  end

  # POST /anunciantes
  # POST /anunciantes.json
  def create
    @anunciante = Anunciante.new(params[:anunciante])
    @anunciante.usuario = current_usuario

    respond_to do |format|
      if @anunciante.save
        format.html { redirect_to @anunciante, notice: 'Jogo was successfully created.' }
        format.json { render json: @anunciante, status: :created, location: @anunciante }
      else
        format.html { render action: "new" }
        format.json { render json: @anunciante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anunciantes/1
  # PUT /anunciantes/1.json
  def update
    @anunciante = Anunciante.find(params[:id])

    respond_to do |format|
      if @anunciante.update_attributes(params[:anunciante])
        format.html { redirect_to @anunciante, notice: 'Jogo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anunciante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anunciantes/1
  # DELETE /anunciantes/1.json
  def destroy
    @anunciante = Anunciante.find(params[:id])
    @anunciante.destroy

    respond_to do |format|
      format.html { redirect_to anunciantes_url }
      format.json { head :no_content }
    end
  
  end
  
  
end

app/controllers/anuncios_controller.rb
class AnunciosController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
  end
  
  def tipo_conta
    
  end
  
end

app/controllers/noticia_controller.rb
class NoticiaController < InheritedResources::Base
end

app/helpers/anunciantes_helper.rb
module AnunciantesHelper
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/views/home/index.html.erb
<div id="container">
	
	<header id="cabecalho-pagina-inicial">
		<h1>Home#index</h1>
		<p>Find me in app/views/home/index.html.erb</p>
		 <% if usuario_signed_in? %>
    		Bem-Vindo <%= current_usuario.email %>. Não é Você?
    		<%= link_to "Sign out", destroy_usuario_session_path, :method => :delete %>
  		<% else %>
    		<%= link_to "Sign up", new_usuario_registration_path %> or <%= link_to "sign in", new_usuario_session_path %>
  		<% end %>
	</header>
	
	<nav id="menu-pagina-inicial">
		
		<%= link_to "cadastrar", new_usuario_registration_path %>
	</nav>
	
	<div id="conteudo-pagina-inicial">
		
		<div id="noticias-pagina-inicial">
			
		</div>
		
		<aside id="painel-direito-pagina-inicial">
			
		</aside>
		
	</div>
	
	
	<footer id="rodape-pagina-inicial">
		
	</footer>
</div>

app/views/home/tipo_conta.html.erb
<div id="container">
	
	<header id="cabecalho-pagina-inicial">
		<h1>Home#index</h1>
		<p>Find me in app/views/home/index.html.erb</p>
	</header>
	
	<nav id="menu-pagina-inicial">
		
		<%= link_to "cadastrar", new_usuario_registration_path %>
	</nav>
	
	<div id="conteudo-pagina-inicial">
		
		<div>
			<h2>Visitante Cadastrado</h2>
			<p>
				
			</p>
			<%= link_to "Avançar", new_visitante_credenciado_path %>
		</div>
		
		<div>
			<h2>Anunciante</h2>
			<p>
				
				
			</p>
			<%= link_to "Avançar", new_anunciante_path %>
		</div>
	
	</div>
	
	
	<footer id="rodape-pagina-inicial">
		
	</footer>
</div>

app/views/noticia/_form.html.erb
<%= form_for(@noticium) do |f| %>
  <% if @noticium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% @noticium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :fonte %><br />
    <%= f.text_field :fonte %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/noticia/edit.html.erb
<h1>Editing noticium</h1>

<%= render 'form' %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>

app/views/noticia/index.html.erb
<h1>Listing noticia</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Autor</th>
    <th>Fonte</th>
    <th>Conteudo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @noticia.each do |noticium| %>
  <tr>
    <td><%= noticium.titulo %></td>
    <td><%= noticium.autor %></td>
    <td><%= noticium.fonte %></td>
    <td><%= noticium.conteudo %></td>
    <td><%= link_to 'Show', noticium %></td>
    <td><%= link_to 'Edit', edit_noticium_path(noticium) %></td>
    <td><%= link_to 'Destroy', noticium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Noticium', new_noticium_path %>

app/views/noticia/new.html.erb
<h1>New noticium</h1>

<%= render 'form' %>

<%= link_to 'Back', noticia_path %>

app/views/noticia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @noticium.titulo %>
</p>

<p>
  <b>Autor:</b>
  <%= @noticium.autor %>
</p>

<p>
  <b>Fonte:</b>
  <%= @noticium.fonte %>
</p>

<p>
  <b>Conteudo:</b>
  <%= @noticium.conteudo %>
</p>


<%= link_to 'Edit', edit_noticium_path(@noticium) %> |
<%= link_to 'Back', noticia_path %>