config/routes.rb
PortalBrazucas::Application.routes.draw do
  resources :comentarios

  resources :noticia

  resources :anuncios

  resources :anunciantes

  resources :visitante_credenciados

  devise_for :usuarios, :controllers => { :registrations => "registrations" }

  get "home/index"
  get "home/tipo_conta"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

    root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/anunciante.rb
class Anunciante < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :endereco
  has_many :anuncios
  attr_accessible :cnpj, :nome, :razao_social, :telefone, :url_website, :usuario, :endereco
end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  belongs_to :anunciante
  attr_accessible :descricao, :titulo, :url_anuncio
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  belongs_to :estado
  has_many :enderecos
  attr_accessible :altitude, :area, :clima, :densidade, :fuso_horario, :nome, :populacao, :sigla, :url_website, :estado
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :noticia
  attr_accessible :texto
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  attr_accessible :bairro, :cidade, :complemento, :latitude, :logradouro, :longitude, :numero
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_many :cidades
  attr_accessible :nome, :sigla, :pais
end

app/models/noticium.rb
class Noticium < ActiveRecord::Base
  attr_accessible :autor, :conteudo, :fonte, :titulo
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_many :estados
  attr_accessible :nome, :sigla, :url_imagem_bandeira
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :visitante_credenciados
  has_many :anunciantes
end

app/models/visitante_credenciado.rb
class VisitanteCredenciado < ActiveRecord::Base
  belongs_to :usuario
  attr_accessible :cpf, :nascimento, :nome, :sexo, :sobrenome, :telefone, :usuario
end

app/controllers/anunciantes_controller.rb
class AnunciantesController < InheritedResources::Base
  
  # GET /anunciantes
  # GET /anunciantes.json
  def index
    @anunciantes = Anunciante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anunciantes }
    end
  end

  # GET /anunciantes/1
  # GET /anunciantes/1.json
  def show
    @anunciante = Anunciante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anunciante }
    end
  end

  # GET /anunciantes/new
  # GET /anunciantes/new.json
  def new
    @anunciante = Anunciante.new
    @anunciante.usuario = current_usuario

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anunciante }
    end
  end

  # GET /anunciantes/1/edit
  def edit
    @anunciante = Anunciante.find(params[:id])
  end

  # POST /anunciantes
  # POST /anunciantes.json
  def create
    @anunciante = Anunciante.new(params[:anunciante])
    @anunciante.usuario = current_usuario

    respond_to do |format|
      if @anunciante.save
        format.html { redirect_to @anunciante, notice: 'Jogo was successfully created.' }
        format.json { render json: @anunciante, status: :created, location: @anunciante }
      else
        format.html { render action: "new" }
        format.json { render json: @anunciante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anunciantes/1
  # PUT /anunciantes/1.json
  def update
    @anunciante = Anunciante.find(params[:id])

    respond_to do |format|
      if @anunciante.update_attributes(params[:anunciante])
        format.html { redirect_to @anunciante, notice: 'Jogo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anunciante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anunciantes/1
  # DELETE /anunciantes/1.json
  def destroy
    @anunciante = Anunciante.find(params[:id])
    @anunciante.destroy

    respond_to do |format|
      format.html { redirect_to anunciantes_url }
      format.json { head :no_content }
    end
  
  end
  
  
end

app/controllers/anuncios_controller.rb
class AnunciosController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comentarios_controller.rb
class ComentariosController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
  end
  
  def tipo_conta
    
  end
  
end

app/controllers/noticia_controller.rb
class NoticiaController < InheritedResources::Base
end

app/helpers/anunciantes_helper.rb
module AnunciantesHelper
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/views/anunciantes/_form.html.erb
<%= form_for(@anunciante) do |f| %>
  <% if @anunciante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anunciante.errors.count, "error") %> prohibited this anunciante from being saved:</h2>

      <ul>
      <% @anunciante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= @anunciante.usuario.id %><br />
  </div>
  
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :razao_social %><br />
    <%= f.text_field :razao_social %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :url_website %><br />
    <%= f.text_field :url_website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anunciantes/edit.html.erb
<h1>Editing anunciante</h1>

<%= render 'form' %>

<%= link_to 'Show', @anunciante %> |
<%= link_to 'Back', anunciantes_path %>

app/views/anunciantes/index.html.erb
<h1>Listing anunciantes</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Endereco</th>
    <th>Nome</th>
    <th>Razao social</th>
    <th>Cnpj</th>
    <th>Telefone</th>
    <th>Url website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anunciantes.each do |anunciante| %>
  <tr>
    <td><%= anunciante.usuario %></td>
    <td><%= anunciante.endereco %></td>
    <td><%= anunciante.nome %></td>
    <td><%= anunciante.razao_social %></td>
    <td><%= anunciante.cnpj %></td>
    <td><%= anunciante.telefone %></td>
    <td><%= anunciante.url_website %></td>
    <td><%= link_to 'Show', anunciante %></td>
    <td><%= link_to 'Edit', edit_anunciante_path(anunciante) %></td>
    <td><%= link_to 'Destroy', anunciante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anunciante', new_anunciante_path %>

app/views/anunciantes/new.html.erb
<h1>New anunciante</h1>

<%= render 'form' %>

<%= link_to 'Back', anunciantes_path %>

app/views/anunciantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @anunciante.usuario %>
</p>

<p>
  <b>Endereco:</b>
  <%= @anunciante.endereco %>
</p>

<p>
  <b>Nome:</b>
  <%= @anunciante.nome %>
</p>

<p>
  <b>Razao social:</b>
  <%= @anunciante.razao_social %>
</p>

<p>
  <b>Cnpj:</b>
  <%= @anunciante.cnpj %>
</p>

<p>
  <b>Telefone:</b>
  <%= @anunciante.telefone %>
</p>

<p>
  <b>Url website:</b>
  <%= @anunciante.url_website %>
</p>


<%= link_to 'Edit', edit_anunciante_path(@anunciante) %> |
<%= link_to 'Back', anunciantes_path %>

app/views/anuncios/_form.html.erb
<%= form_for(@anuncio) do |f| %>
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anuncio.errors.count, "error") %> prohibited this anuncio from being saved:</h2>

      <ul>
      <% @anuncio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :anunciante %><br />
    <%= f.text_field :anunciante %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :url_anuncio %><br />
    <%= f.text_field :url_anuncio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anuncios/edit.html.erb
<h1>Editing anuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @anuncio %> |
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/index.html.erb
<h1>Listing anuncios</h1>

<table>
  <tr>
    <th>Anunciante</th>
    <th>Titulo</th>
    <th>Descricao</th>
    <th>Url anuncio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anuncios.each do |anuncio| %>
  <tr>
    <td><%= anuncio.anunciante %></td>
    <td><%= anuncio.titulo %></td>
    <td><%= anuncio.descricao %></td>
    <td><%= anuncio.url_anuncio %></td>
    <td><%= link_to 'Show', anuncio %></td>
    <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
    <td><%= link_to 'Destroy', anuncio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anuncio', new_anuncio_path %>

app/views/anuncios/new.html.erb
<h1>New anuncio</h1>

<%= render 'form' %>

<%= link_to 'Back', anuncios_path %>

app/views/anuncios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Anunciante:</b>
  <%= @anuncio.anunciante %>
</p>

<p>
  <b>Titulo:</b>
  <%= @anuncio.titulo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @anuncio.descricao %>
</p>

<p>
  <b>Url anuncio:</b>
  <%= @anuncio.url_anuncio %>
</p>


<%= link_to 'Edit', edit_anuncio_path(@anuncio) %> |
<%= link_to 'Back', anuncios_path %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :noticia %><br />
    <%= f.text_field :noticia %>
  </div>
  <div class="field">
    <%= f.label :texto %><br />
    <%= f.text_area :texto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Noticia</th>
    <th>Texto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.usuario %></td>
    <td><%= comentario.noticia %></td>
    <td><%= comentario.texto %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @comentario.usuario %>
</p>

<p>
  <b>Noticia:</b>
  <%= @comentario.noticia %>
</p>

<p>
  <b>Texto:</b>
  <%= @comentario.texto %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>